// flow-typed signature: c9acc941612934e64ab4e44d26c1d78f
// flow-typed version: <<STUB>>/blueimp-md5_v1.1.1/flow_v0.47.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'blueimp-md5'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'blueimp-md5' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'blueimp-md5/js/demo' {
  declare module.exports: any;
}

declare module 'blueimp-md5/js/md5' {
  declare module.exports: any;
}

declare module 'blueimp-md5/js/md5.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'blueimp-md5/js/demo.js' {
  declare module.exports: $Exports<'blueimp-md5/js/demo'>;
}
declare module 'blueimp-md5/js/md5.js' {
  declare module.exports: $Exports<'blueimp-md5/js/md5'>;
}
declare module 'blueimp-md5/js/md5.min.js' {
  declare module.exports: $Exports<'blueimp-md5/js/md5.min'>;
}
